server:
  port: 8083
#  servlet:
#    context-path: /api

spring:
  application:
    name:spring-ai

  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
        options:
          temperature: 0.8
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max-latest

      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springAI
    username: root
    password: 12345678


logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.anran.springAI: debug